config/routes.rb
LetsRails::Application.routes.draw do
  get "/deals" => "deals#index", as: "deals"
  get "/deals/:id" => "deals#show", as: "deal"

  get "/deals/:deal_id/purchases/new" => "purchases#new", as: "new_deal_purchase"
  post "/deals/:deal_id/purchases" => "purchases#create", as: "deal_purchases"

  get "/registro" => "people#new", as: "sign_up"
  root :to => "deals#index"
end

app/models/api_model.rb
class ApiModel
  include HTTParty
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  include Attribution

  base_uri 'localhost:2601'

  def initialize(attrs={})
    attrs.each do |k,v|
      send("#{k}=", v)
    end
  end

  def self.cast(obj)
    case obj
    when Hash then new(obj)
    when self then obj
    else raise ArgumentError.new("can't convert #{obj.class} to #{name}")
    end
  end

  # HTTP stuff
  def self.get(path, options={})
    url = File.join(base_uri, path)
    if options[:query].present?
      url << "?#{options[:query].to_param}"
    end
    resp = nil
    ms = Benchmark.ms { resp = super }
    logger.info("GET %s %3d %0.1fms" % [url, resp.code, ms])
    logger.ap resp.parsed_response if resp.code == 200
    resp
  end

  def self.from_response(resp)
    case resp.code
    when 200
      data = resp.parsed_response
      if data.is_a?(Array)
        data.map{|d| new(d) }
      else
        new(data)
      end
    when 404
      nil
    else
      raise "HTTP #{resp.code}"
    end
  end

  # Finders
  def self.all(query={})
    from_response(get("/#{name.underscore.pluralize}", :query => query))
  end

  def self.find(id)
    from_response(get("/#{name.underscore.pluralize}/#{id}"))
  end

  def self.logger
    Rails.logger
  end

  def logger
    self.class.logger
  end

  # Common attributes
  integer :id
  time :created_at
  time :updated_at

  # ActiveModel-ish stuff
  def to_param
    id
  end

  def persisted?
    false
  end

end

app/models/city.rb
class City < ApiModel
  belongs_to :country

  string :name
  string :slug
  time_zone :time_zone

  has_many :deals

  delegate :locale, :to => :country, :allow_nil => true

  def self.geolocate(ip_address)
    # TODO: Real implementation
    fallback
  end

  def self.fallback
    find(1)
  end
end

app/models/country.rb
class Country < ApiModel
  string :name
  string :code
  string :language

  has_many :cities

  def locale
    language.downcase.to_sym
  end
end

app/models/credit_card.rb
class CreditCard < ApiModel
  belongs_to :person

  string :number
  integer :expiration_month
  integer :expiration_year
  string :first_six
  string :last_four
  integer :number_length
end

app/models/deal.rb
class Deal < ApiModel
  belongs_to :city

  string :short_title
  string :long_title
  string :description
  time :offer_starts_at
  time :offer_ends_at

  has_many :deal_images
  has_many :options

  delegate :price, :to => :primary_option, :allow_nil => true
  delegate :value, :to => :primary_option, :allow_nil => true

  def list_deal_images
    @list_deal_images ||= deal_images.select(&:list)
  end

  def list_deal_image
    @list_deal_image ||= list_deal_images.first
  end

  def wide_deal_images
    @wide_deal_images ||= deal_images.select(&:wide)
  end

  def wide_deal_image
    @wide_deal_image ||= wide_deal_images.first
  end

  def ordered_options
    @ordered_options ||= options.sort_by(&:price)
  end

  def primary_option
    @primary_option ||= options.detect(&:primary?) || ordered_options.first
  end

  def discount
    primary_option.try(:discount).to_f
  end

  def countdown
    @countdown ||= begin
      t = offer_ends_in
      {
        :days => t[0],
        :hours => t[1],
        :minutes => t[2],
        :seconds => t[3]
      }
    end
  end

  # returns an array of [days, hours, minutes, seconds] until offer_ends_at
  def offer_ends_in
    if offer_ends_at < Time.now
      [0, 0, 0, 0]
    else
      seconds = (offer_ends_at - Time.now).to_i
      if seconds < 60
        [0, 0, 0, seconds]
      else
        minutes, seconds = seconds.divmod(60)
        if minutes < 60
          [0, 0, minutes, seconds]
        else
          hours, minutes = minutes.divmod(60)
          if hours < 24
            [0, hours, minutes, seconds]
          else
            days, hours = hours.divmod(24)
            [days, hours, minutes, seconds]
          end
        end
      end
    end
  end
end

app/models/deal_image.rb
class DealImage < ApiModel
  belongs_to :deal

  string :url
  integer :width
  integer :height

  LIST_WIDTH = 280
  WIDE_WIDTH = 680

  def list
    width == LIST_WIDTH
  end

  def wide
    width == WIDE_WIDTH
  end
end

app/models/option.rb
class Option < ApiModel
  belongs_to :deal

  string :title
  decimal :price
  decimal :value
  boolean :primary

  def discount
    @discount ||= 100 * (price.to_d / value.to_d)
  end
end

app/models/person.rb
class Person < ApiModel
  string :email
  string :first_name
  string :last_name
  string :password

  has_many :purchases
end

app/models/purchase.rb
class Purchase < ApiModel
  belongs_to :person
  belongs_to :credit_card
  belongs_to :option

  integer :quantity

  has_many :vouchers
end

app/models/voucher.rb
class Voucher < ApiModel
  belongs_to :purchase
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :load_locale

  helper FastGettext::Translation
  include FastGettext::Translation

protected

  def current_city
    @current_city ||= begin
      if params[:city_id].present?
        City.find(params[:city_id])
      elsif cookies[:city_id].present?
        City.find(cookies[:city_id])
      else
        city = City.geolocate(request.remote_addr) || City.default
        cookies[:city_id] = city.id
        city
      end
    end
  end
  helper_method :current_city

  def load_locale
    I18n.locale = current_city.locale
  end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    @deals = current_city.deals.shuffle
  end

  def show
    @deal = Deal.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new

  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  before_filter :load_deal

  def new
    @purchase = Purchase.new(:quantity => 1)
  end

protected
  def load_deal
    @deal = Deal.find(params[:deal_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deals/index.html.erb
<section id="deals" class="deals">
  <% for deal in @deals %>
    <article id="deal-<%= deal.id %>" class="deal">
      <% if deal.list_deal_image %>
        <%= link_to image_tag(deal.list_deal_image.url, :width => deal.list_deal_image.width, :height => deal.list_deal_image.height, :alt => deal.long_title), deal_path(deal) %>
      <% end %>
      <div class="subheading">
        <span class="discount">-<%= number_to_percentage deal.discount, :precision => 0 %></span>
        <h3><%= link_to deal.short_title, deal_path(deal) %></h3>
      </div>
      <div class="details">
        <span class="countdown">
          <%= "#{deal.countdown[:days]}d" if deal.countdown[:days] > 0 %>
          <%= "#{deal.countdown[:hours]}h" if deal.countdown[:hours] > 0 %>
          <%= "#{deal.countdown[:minutes]}m" if deal.countdown[:minutes] > 0 %>
          <%= "#{deal.countdown[:seconds]}s" if deal.countdown[:seconds] > 0 %>
        </span>
        <span class="value"><%= number_to_currency deal.value, :precision => 0 %></span>
        <span class="price"><%= number_to_currency deal.price, :precision => 0 %></span>
        <%= link_to "#{t(:see)} >", deal_path(deal), :class => 'see' %>
      </div>
    </article>
  <% end %>
</section>

app/views/deals/show.html.erb
<section id="deal" class="deal">
  <article id="deal-<%= @deal.id %>" class="deal">
    <h2><%= @deal.long_title %></h2>
    <% unless @deal.wide_deal_image.blank? %>
      <%= image_tag @deal.wide_deal_image.url, :width => @deal.wide_deal_image.width, :height => @deal.wide_deal_image.height, :alt => @deal.long_title %>
    <% end %>
    <h3><%= t(:description) %></h3>
    <div class="description">
      <%=raw @deal.description %>
    </div>
  </article>
  <aside>
    <%= link_to t(:buy_now!), new_deal_purchase_path(@deal), :class => 'buy' %>
  </aside>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!--[if lt IE 9]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <title>LetsBonus</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <h1><%= link_to "LetsBonus", root_path %></h1>
        <%= link_to _("Register"), sign_up_path %>
      </header>
      <%= yield %>
      <footer>
      </footer>
    </div>
  </body>
</html>

app/views/purchases/new.html.erb
<section id="purchase">
  <fieldset>
    <%= form_for @purchase, :url => deal_purchases_path(@deal, @purchase) do |f| %>
      <p>
        <%= f.label :option_id, "Option" %>
        <%= f.select :option_id, @deal.options.map{|o| [ t(:option_label, :value => number_to_currency(o.value), :price => number_to_currency(o.price), :title => o.title), o.id ] } %>
      </p>

      <p>
        <%= f.label :quantity %>
        <%= f.select :quantity, 1..5 %>
      </p>

      <p>
        <%= f.submit "Purchase" %>
      </p>
    <% end %>
  </fieldset>
</section>